#     ___   ______
#    /   | / ____/ 
#   / /| |/ /      By jonagamerpro1234
#  / ___ / /___    Version ${project.version}
# /_/  |_\____/    Thanks for using AdvancedChat <3
#
# ● AdvancedChat is an easy to use plugin that will help you customize the chat on your server to make it look its best. It will also have a customization system by groups and among other functions more...
#
# ● Spigot: https://www.spigotmc.org/resources/advancedchat-1-7-x-1-17-x.83889/
# ● Songoda: https://songoda.com/marketplace/product/advancedchat-chat-related.542
# ● Wiki [Working Progress]: https://jonagamerpro1234.gitbook.io/advancedchat/
# ● Discord: https://discord.gg/c5GhQDQCK5
# ● Issue Tracker: https://github.com/jonagamerpro1234/AdvancedChat/issues
# ● Bstast: https://bstats.org/plugin/bukkit/AdvancedChat/8826



Settings:
  
  # I would not change anything
  Config-Version: 2
  
  # The notification of updates will be disabled if it is false this only disables the notifications when entering the server,
  # if it is true a notification will be sent if there is an update available
  # Permission: advancedchat.update
  Update: true

  # This option should only be used if there is a problem with certain functions of the plugin, debug messages will be activated in the console
  Debug: false

    # |ChatFormat Type|
    # [default] use default chat by minecraft 
    # [custom] use the chat defined in [Custom-Format] 
  # [group] use the chat defined in [Group.<name>] but you need to add the permission that you defined for the group
  ChatFormat-Type: custom
  
  # here you can enable or disable the chat to be seen in the console
  Show-Chat-In-Console: false
    
    # |Default-Color-Message| Here you can define the chat color that is assigned by default to players
    # The color system does not work with (&) but uses a simpler system that is by color names, here below you have the list of available colors
  # Color List: https://jonagamerpro1234.gitbook.io/advancedchat/color-list
  Default-Color-Message: 'white'

#
# Here are all the configurations of the plugin implementations and more
Hooks:
  
  # |LuckPerms| Here you can configure everything related to LuckPerms and or deactivate or activate functions
  LuckPerms:
    
    # |Enabled| Here you can enable or disable this feature
    Enabled: true
    
    # |Use-Luckperms-In-Groups| When using this option, the groups are discovered with the LuckPerms system
    Use-Luckperms-In-Groups: false

  # Here you can define the discord channel where the messages from minecraft to discord are seen
  DiscordSRV:

    # Here you can enable or disable this feature
    Enabled: true

    # Here is the id of the channel that is used for the chat
    Channel-ID: 'none'

# Here you can customize the chat of your server with the different functions that advancedchat brings
# For more information you can see the wiki: https://jonagamerpro1234.gitbook.io/advancedchat/
ChatFormat:

  # Here you can enable or disable this feature
  Enable: true

  # |Format| Here you define the chat format for all players.
  Format: '%luckperms_prefix% &b<name> &8&l>'

  # The chat type is to use the three types that exist which are, normal | group | comp(compatibility)
  # > normal: use the chat customization that the plugin brings
  # > group:
  # > comp:
  Chat-Type: normal

  # This section allows you to modify the hover events in the chat
  HoverEvent:

    # Here you can enable or disable this feature
    Enabled: true

    # This section allows you to define the hover text for all the players
    Hover:
      - '&6> &aHello &b<name>'
      - '&6> &e%player_exp_to_level%'
      - '&6> &dadd more lines like these'

  # |ClickEvent| This section allows you to modify chat click events
  ClickEvent:

    # Here you can enable or disable this feature
    Enabled: true

    # |Mode| there are three different modes which are [ command | suggest | url ]
    Mode: command

    # |Actions| This is where are the available events that you can use
    Actions:

      # |Command| Clicking on the chat will execute the command defined in the config
      Command: '/say <name> hello server'

      # |Url| Clicking on the chat opens a link
      Url: 'https://jonagamerpro1234.gitbook.io/advancedchat/'

      # |Suggest-Command| Clicking on the chat suggests a command that you define in the config
      Suggest-Command: '/msg <name>'

#
# | ClearChat |
ClearChat:

  # is the message that will be sent when cleaning the chat [this does not affect the command for the player only the message from the server]
  Broadcast: true

  # you can activate the automatic cleaning of the chat according to the number of ticks
  AutoClear: true

  # With this function you can make the staff is not affected by the clearchat
  # Permission: advancedchat.clearchat.bypass
  ByPass-Staff: false

  # |Tick| here you can define the time that the actions are automatically executed [Default | 24000], 24000 tick = 20 min
  Tick: 24000

  # Here you can define the first ticks that are executed when starting the server
  Start-Tick: 6000

  # blank lines to broadcast in chat
  LineClear: 100

#
# |Command Blocker|
# |here you can block the commands that you do not want to be used on the server at the moment it does not have the function of [antitabcomplete]
Command-Blocker:

  # Here you can enable or disable this feature
  Enabled: true
  
  # |Mute-BlackList| In this list you can define which commands the silenced players cannot use
  Mute-BlackList:
    - '/tell'
    - '/me'
    - '/say'
    - '/msg'
    - '/minecraft:me'
    - '/minecraft:tell'

  # |BlackList| In this list you can define which commands cannot be used by players in general including your server staff [this function may change in future updates]
  BlackList:
    - '/plugins'
    - '/pl'
    - '/?'
    - '/ver'
    - '/version'
    - '/bukkit:version'
    - '/bukkit:pl'
    - '/bukkit:plugins'
    - '/bukkit:ver'
    - '/bukkit:?'
    - '/icanhasbukkit'
    - '/about'

#
# |Filter Chat| 
# |here you can filter the unwanted words on your server and have a little more control over the chat
Filter-Chat:
  
  # Here you can enable or disable this feature
  Enabled: true
  
  # |Message| here you can define a personalized message that will be sent to the player
  Message: '&e[!] you cannot use this word, it is &nblocked!'

  # |BadWords| The format is very simple, you just have to add the word you want to censor to the list
  BadWords:
    - 'noob'
    - 'stupid'
    - 'fuck'
#
# |Translation of messages from AdvancedChat|
# |Version: 1.6.0|
#
AdvancedChat:
  ClearChat-Server: '&7The chat has been cleaned'
  ClearChat-Player: '&7The chat has been cleaned by &b[&e<name>&b]'
  No-Permission: '&cYou dont have permission to do that!'
  No-Permission-Label: 'Ask the server owner or an administrator for help for more information.'
  Error-Args: '&cUnknown Arguments'
  Reload: '&aReload Completed'
  Help-Mute: '&7Use &b/Mute &e<player> &7'
  Help-UnMute: '&7Use &b/UnMute &e<player> &7'
  Help-Cmd: '&7Use &b/AdvanceChat &8| &9/Ac &6Help &7 show more information of plugin'
  Help-Msg:
    - '&5> &b/AdvancedChat &8| &9/Ac &7these are the variants of the main plugin command'
    - '&5> &b/AdvancedChat &6help &7show this same message'
    - '&5> &b/AdvancedChat &6reload &7reload the plugin files'
    - '&5> &b/AdvancedChat &6info &7shows information about the plugin'
    - '&5> &b/AdvancedChat &6color &7 open color gui'
    - '&5> &b/AdvancedChat &6player &e<player name> &7open the player settings'
    - '&5> &b/Mute &e<player name> &7mute the player'
    - '&5> &b/UnMute &e<player name> &7demute the player'
    - '&5> &b/ClearChat &8| &9/Cc &7clean the chat when it is very full or necessary'
  Mute-Bypass: '&eThis player cannot be muted because This player cannot be muted because he is bypassed'
  Mute-Player: '&b<name> &cis now muted!'
  UnMute-Player: '<name> &ais now unmuted!'
  Player-Is-Not-Mute: '&e[!] &cThe player is not muted'
  Player-Is-Mute: '&e[!] &cThe player is already muted'
  Alert-Mute: '&e[!] &cright now you are muted'
  No-Online-Player: '&cThis player does not exist or is not connected!'
  No-Use-Command: '&e[&b!&e] &cYou can t use that command! &b[&c<cmd>&b]'
  No-Use-Command-Mute: '&cYou cannot use that command while it is muted! &b[&c<cmd>&b]'
#
# This is the end of the configuration ... [-_-] more things coming soon
# 
# | Config File
# | Version 1.6.0
#